version: "2"
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  exclusions:
    rules:
      - path: (.+)_test\.go
        linters:
          - errcheck
      - text: Error return value of
        linters:
          - errcheck
      - text: Use fmt\.Fprintf
        linters:
          - staticcheck
      - text: could use tagged switch
        linters:
          - staticcheck
run:
  timeout: 5m
